# Site settings
# To update the website run the following commands:
#
# s3_website push /Users/johnmadden/website/s3_website
#
#
title: Jonathan Madden
email: madden.jonathanj@gmail.com
url: https://www.maddenjonathan.com
description: "Personal website of Jonathan Madden - Software Engineer"
keywords: "Jonathan, Madden, Software, Engineer, John, UT, Austin, Programming, Computer Science, Website, CI/CD, Dallas, Texas, TX, Plano, Capital, One, Capital One, Software Engineer, Jonathan Madden, Jonathan Madden Software Engineer"
skills: "Web Developer - AWS - Security"
meta_author: Madden Jonathan

# Google webmaster tools
google_verify: 1wXqKmQKPuzT2b8SwcMdubfe07VzYIz6HbdcanKZKCo

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: JohnMadden

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/john.madden.716970
  - title: github
    url: https://github.com/MaddenJohn
  - title: linkedin
    url: https://www.linkedin.com/in/jmaddenlinked

# Postal address (add as many lines as necessary)
address:
  - line: 5301 W Spring Creek Pkwy 
  - line: Plano, TX 75024

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
